#!/usr/bin/python3

import ast
import configparser
import datetime
import os
import logging
import socket
import time

from subprocess import check_call

from kombu import Connection, Exchange, Queue
from novaclient import client
import keystoneauth1.identity.v3 as keystoneauth1
import keystoneauth1.session as keystoneauth1_session

CONFIG_FILE = '/etc/serverstack-dns/dns.conf'

logging.basicConfig(
    level=logging.DEBUG, format="%(asctime)s:%(levelname)s %(message)s")


def get_config():
    config_in = configparser.ConfigParser()
    if not config_in.read(CONFIG_FILE):
        raise Exception('Couldnt load config @ {}'.format(CONFIG_FILE))

    def _get(setting):
        return config_in.get('DEFAULT', setting)

    conf = {
        'os_username': os.getenv('OS_USERNAME') or _get('os_username'),
        'os_password': os.getenv('OS_PASSWORD') or _get('os_password'),
        'os_project_name': (os.getenv('OS_PROJECT_NAME') or
                            _get('os_project_name')),
        'os_auth_url': os.getenv('OS_AUTH_URL') or _get('os_auth_url'),
        'os_user_domain_name': (os.getenv('OS_USER_DOMAIN_NAME') or
                                _get('os_user_domain_name')),
        'os_project_domain_name': (os.getenv('OS_PROJECT_DOMAIN_NAME') or
                                   _get('os_project_domain_name')),
        'rabbit_user': _get('rabbit_user'),
        'rabbit_password': _get('rabbit_password'),
        'rabbit_host': _get('rabbit_host'),
        'rabbit_vhost': _get('rabbit_vhost'),
        'rabbit_exchange': _get('rabbit_exchange'),
        'add_current_instances':
            ast.literal_eval(_get('add_current_instances')),
        'rabbit_topic': _get('rabbit_topic'),
        'include_tenants': _get('include_tenants'),
        'hosts_file': _get('hosts_file'),
        'domain': _get('domain'),
        'upstream_dns': _get('upstream_dns')
    }

    missing = [k for k in conf if conf[k] is None]
    if missing:
        logging.error('Missing config: {}'.format(missing))
        raise Exception('Missing config: {}'.format(missing))

    return conf


config = get_config()


def managed_tenants():
    with open(config['include_tenants']) as inc:
        included = inc.readlines()
    return [i.strip() for i in included if not i.startswith('#')]


_client = None


def add_host_entry(hostname, ip, port_id):
    hostname = '{}.{}'.format(hostname, config['domain'])
    entry = '{} {} #port {}'.format(ip, hostname, port_id)

    with open(config['hosts_file']) as hosts:
        hostnames = hosts.readlines()

    hostnames = [host.strip() for host in hostnames
                 if not host.startswith('#')]

    out = []
    # remove stale entries
    for hostname in hostnames:
        # Sample line:
        # 10.5.0.15 vm-name.openstacklocal #port 2485e5af-fd25-...
        _hostname = hostname.split(' ')
        ip = _hostname[0]
        hn = _hostname[1]
        p = _hostname[3]

        if hn == hostname or p == port_id:
            continue

        out.append(hostname)

    out.append(entry)

    with open(config['hosts_file'], 'w') as cn:
        cn.write('# Generated {}\n'.format(datetime.datetime.utcnow()))
        for entry in out:
            cn.write('{}\n'.format(entry))


def remove_host_entry(port_id):
    with open(config['hosts_file']) as hosts:
        hosts = hosts.readlines()
    hosts = [host.strip() for host in hosts if not host.startswith('#')]

    out = []
    for host in hosts:
        if not host.endswith(port_id):
            out.append(host)

    with open(config['hosts_file'], 'w') as cn:
        cn.write('# Generated {}\n'.format(datetime.datetime.utcnow()))
        for entry in out:
            cn.write('{}\n'.format(entry))


def get_nova_client():
    global _client
    if _client is not None:
        return _client
    auth = keystoneauth1.Password(auth_url=config['os_auth_url'],
                                  username=config['os_username'],
                                  user_domain_name=config['os_user_domain_name'],
                                  password=config['os_password'],
                                  project_name=config['os_project_name'],
                                  project_domain_name=config['os_project_domain_name'])
    session = keystoneauth1_session.Session(auth=auth)
    _client = client.Client("2", session=session)
    return _client


def get_instance_hostname(instance_id):
    client = get_nova_client()
    try:
        instance = client.servers.get(instance_id)
        return instance.name.replace(' ', '-')

    except:
        logging.error('Could not get server name for instance %s.' %
                      instance_id)


def get_current_instances():
    client = get_nova_client()
    tenant_name = config['os_project_name']

    for instance in client.servers.list():
        try:
            port_id = instance.interface_list()[0].port_id
        except:
            port_id = ""
        networks = instance.networks.get('%s_admin_net' % tenant_name, None)
        if networks:
            yield get_instance_hostname(instance.id), networks[0], port_id


def add_current_instances():
    for hostname, ip_addr, port_id in get_current_instances():
        add_host_entry(hostname, ip_addr, port_id)


def manage_dns(body, message):
    tenant_ids = [body['_context_tenant_id']]

    try:
        tenant_ids.append(body['payload']['port']['tenant_id'])
    except KeyError:
        pass

    if not set(managed_tenants()).issubset(set(tenant_ids)):
        logging.debug('Skipping event, not managing DNS for tenant %s.' %
                      tenant_ids)
        return

    if body['event_type'] in ('port.create.end', 'port.update.end'):
        ip = body['payload']['port']['fixed_ips'][0]['ip_address']
        instance_id = body['payload']['port']['device_id']
        port_id = body['payload']['port']['id']

        if not instance_id:
            logging.info('Skipping creation of DNS entry, device not set')
            return

        hostname = get_instance_hostname(instance_id)
        if not hostname:
            logging.info('Skipping creation of DNS entry for instance %s.' %
                         instance_id)
            return
        logging.info('Creating DNS entry: %s to instance %s with hostname %s.'
                     % (ip, instance_id, hostname))
        add_host_entry(hostname, ip, port_id)
        ensure_dnsmasq()

    if body['event_type'] == 'port.delete.end':
        port_id = body['payload']['port_id']
        logging.info('Deleting DNS entry for port %s.' % port_id)
        remove_host_entry(port_id)
        ensure_dnsmasq()


def process_msg(body, message):
    try:
        manage_dns(body, message)
        message.ack()
    except Exception as e:
        logging.error('Failed to process notification: %s' % e)


def listen():
    nova_x = Exchange(config['rabbit_exchange'], type='topic', durable=False)
    info_q = Queue(
        socket.gethostname(), exchange=nova_x, durable=False, auto_delete=True,
        routing_key=config['rabbit_topic'])

    conn_url = 'amqp://%s:%s@%s/%s' % (config['rabbit_user'],
                                       config['rabbit_password'],
                                       config['rabbit_host'],
                                       config['rabbit_vhost'])
    logging.info('Connecting to rabbit @ %s.' % conn_url)

    with Connection(conn_url) as conn:
        with conn.Consumer(info_q, callbacks=[process_msg]):
            while True:
                conn.drain_events()


def ensure_dnsmasq():
    pid_file = os.path.join('/var/run/dnsmasq/', config['domain'] + '.pid')

    cmd = ['dnsmasq', '--strict-order', '--conf-file=',
           '--bind-interfaces', '--except-interface=lxcbr0',
           '--domain=%s' % config['domain'], '--no-hosts',
           '--addn-hosts=%s' % config['hosts_file'], '-E', '--pid-file=%s' %
           pid_file, '-S', config['upstream_dns']]

    if os.path.isfile(pid_file):
        pid = open(pid_file).read().strip()
        proc_cmd = os.path.join('/proc', pid, 'cmdline')
        if os.path.isfile(proc_cmd):
            logging.info('HUPing running dnsmasq (pid: %s)' % pid)
            cmd = ['kill', '-HUP', pid]
            check_call(cmd)
            return

    logging.info('Starting new dnsmasq: %s' % ' '.join(cmd))
    check_call(cmd)


if __name__ == '__main__':
    if not os.path.isfile(config['hosts_file']):
        with open(config['hosts_file'], 'wb'):
            pass
    logging.info(config)
    add_current = config.get('add_current_instances', False)
    if add_current is True:
        with open(config['hosts_file'], 'w') as f:
            f.write('')
        add_current_instances()

    ensure_dnsmasq()
    while True:
        try:
            listen()
        except KeyboardInterrupt:
            break
        except ConnectionError as ex:
            logging.debug('Connection error: %s' % str(ex))
            logging.warn('Connection error, reconnecting in 10 seconds')
            time.sleep(10)
        except Exception as ex:
            logging.error('Unhandled exception: %s' % str(ex))
